development:
  access_key_id: AKIATEFIUUUAHFPVJEE6
  secret_access_key: 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

production:
  access_key_id: AKIATEFIUUUAHFPVJEE6
  secret_access_key: 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
